---
- name: Generate config for routers from structured tasks and vars, no key word "vars" "tasks" here
  template: src=router1.j2 dest=/home/hsun/hsun_pynet_dry_run/class5/CFGS/{{item.hostname}}.txt
  with_items:
          - "{{router_vars}}"
