---
- hosts: localhost
  tasks:
    - name: Generate new conf file
      template: src=/home/hsun/hsun_pynet_dry_run/class5/switch1.j2 dest=/home/hsun/hsun_pynet_dry_run/class5/{{item.hostname}}.txt

      with_items:
              - {hostname: pynet-sw1, ip_addr: 10.1.1.1, access_vlan: 888, default_gateway: 10.1.1.254, snmp_community: galileo, secret: lalala}
